FROM registry.access.redhat.com/rhscl/nodejs-4-rhel7

# Default listening port
EXPOSE 8080 9000

USER root

ENV OPENSHIFT_TEMPLATES_DIR=/opt/feedhenry/templates

COPY fh-dfc*.tar.gz ./
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime && \
    tar xfz fh-dfc*.tar.gz && \
    mv fh-dfc*/ fh-dfc/ && \
    mkdir -p config && \
    chown -R default:root ./

# Installing fonts to be able to render PDFs for submissions
#RUN yum install -y dejavu-sans-fonts
#RUN yum install -y https://s3-eu-west-1.amazonaws.com/fhcap/phantomjs-1.9.7-3.el7map.x86_64.rpm

#USER default

# Extract app to work dir and copy conf
COPY fh-supercore*.tar.gz ./
COPY fh-mbaas-template* $OPENSHIFT_TEMPLATES_DIR/
RUN tar -xf fh-supercore*.tar.gz --strip 1 && \
            rm fh-*.tar.gz && \
            mv conf-docker.json config/conf.json && \
            mv fh-dfc/ node_modules/ && \
            chmod -R ug+rw ./

ADD root /

ENTRYPOINT ["container-entrypoint"]
CMD ["run.sh"]

#CMD ["bash", "-c", "node --debg fh-supercore.js config/conf.json --master-only" "node_modules/node-inspector/bin/inspector.js -p 9000 --save-live-edit"]
